### ISSUE TITLE
idToken retrieval

### ISSUE THREAD

**Issue by WisaniShilumani** [abacritt/angular4-social-login#10]
Hi, 

How does one get the idToken from this?

**Comment by WisaniShilumani** [comment]
I solved this by going into node_modules/angular4-social-login and making a few changes.

1. First go into /entities and change the SocialUser model and include "token: string;" like so:
export declare class SocialUser {
    provider: string;
    id: string;
    email: string;
    name: string;
    photoUrl: string;
    token: string;
}

2. Go to angular4-social-login.umd.js and for every function of the GoogleLoginProvider where the SocialUser object is resolved - find "resolve(user)" - add the line:
user.token = _this.auth2.currentUser.get().getAuthResponse().id_token

Your authService should now return the idToken for the user as user.token.

(3) - for Facebook accessToken, you follow similiar logic. Go to angular4-social-login.umd.js; and for every FacebookLoginProvider function that resolves the user (again search for "resolve(user)"):
Under FB.login(function (response) {
//get the token here
var accessToken = response.authResponse.accessToken
...}

(4) Where the user is being modified, simply add user.token = accessToken before resolving

**Comment by jaibatrik** [comment]
You can submit a PR if you want.

**Comment by feischml** [comment]
Hi guys,

solved this in the same way as @WisaniShilumani, just added in the User the whole AuthResponse Object: 

```
export declare class SocialUser {
    provider: string;
    id: string;
    email: string;
    name: string;
    photoUrl: string;
    firstName: string;
    lastName: string;
    authToken: object; // ADDED THIS
}
```

and in angular4-social-login.umd.js:

```
GoogleLoginProvider.prototype.signIn = function () {
        var _this = this;
        return new Promise(function (resolve, reject) {
            var /** @type {?} */ promise = _this.auth2.signIn();
            promise.then(function () {
                var /** @type {?} */ user = new SocialUser();
                var /** @type {?} */ profile = _this.auth2.currentUser.get().getBasicProfile();
                var /** @type {?} */ authObject = _this.auth2.currentUser.get().getAuthResponse(); // ADDED THIS

                user.id = profile.getId();
                user.name = profile.getName();
                user.email = profile.getEmail();
                user.photoUrl = profile.getImageUrl();
                user.firstName = profile.getGivenName(); // ADDED THIS REGARDING ISSUE #9
                user.lastName = profile.getFamilyName(); // ADDED THIS REGARDING ISSUE #9
                user.authToken = authObject; // ADDED THIS

                resolve(user);
            });
        });
    };
```

Regards,
Laszlo

**Comment by Harlok** [comment]
Any plans on updating this package to also return the Facebook accessToken?  

I was thinking of implementing the above solution but the problem is if you work in a team using git, you commit your current code and someone else clones and runs npm install, they won't have the same code in node_modules.  I'd be happy with just a new version of this package that returns the accessToken but more flexible would be to allow us to specify an array of field names we'd like to retrieve.  For example: (['public_profile', 'user_friends', 'email'])

**Comment by soemsakplus** [comment]
If you could update the repo, please include the the Facebook accessToken as well. Thanks.

**Comment by jaibatrik** [comment]
Somebody already submitted a PR and I merged that to master. Will publish to npm shortly. Meanwhile you can use the library by cloning master.

**Comment by GianinaSalomo** [comment]
I need this in npm :'( !

**Comment by Boboss74** [comment]
#48 🙄
