### ISSUE TITLE
angular-cli (angular4) SocialLoginModule is not an NgModule

### ISSUE THREAD

**Issue by rrubio** [abacritt/angular4-social-login#12]
Hi Guys,

Trying to follow the documentation after installing the social plugin. Under app.module.ts import of the following (below) are not being recognized. Any ideas?

> import { SocialLoginModule, AuthServiceConfig } from "angular4-social-login";
import { GoogleLoginProvider, FacebookLoginProvider } from "angular4-social-login"

Also, after cloning the repo and running "demo" i get the following errors:

> Rodrigo:demo$ ng serve
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
Hash: 97f2a0064514b882f1ea
Time: 13682ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 177 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 10.6 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 10.5 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.27 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in SocialLoginModule is not an NgModule
webpack: Failed to compile.

Cheers

**Comment by jaibatrik** [comment]
I think the demo directory does not refer to the latest code present. Can you run `npm install angular4-social-login` inside the demo directory and try?

**Comment by jaibatrik** [comment]
Check [this page](https://github.com/abacritt/angular4-social-login/blob/master/README-AOT.md) for the error you are getting when running the demo app.
