### ISSUE TITLE
On facebook login calls twice to track event fb_page_view

### ISSUE THREAD

**Issue by eudelvigio-fever** [abacritt/angular4-social-login#18]
Hello,

We are using angular4-social-login for manage our social logins, and we think we found an issue:
When the buttons are shown, it seems to track twice an event "fb_page_view", as you can see on the next screenshot, from the demo:
![image](https://user-images.githubusercontent.com/33025856/32229513-47c64694-be51-11e7-9457-703de055c2cf.png)

We debug the library, and we think we found the cause. On the file https://github.com/abacritt/angular4-social-login/blob/master/src/providers/facebook-login-provider.ts, on line 24 it has:
`FB.AppEvents.logPageView();`
After, it has a `FB.getLoginStatus` call. We think there are these two calls which do the twice 'fb_page_view' call. We have done some tests, and it seems that if we delete the 24th line, (`FB.getLoginStatus`), we still can log in with FB account, get the user info, and the track event is not called twice. 

If possible, could you, please, tell us if the deletion of the line is ok, and, if you can again, do a change for that?

Regards

**Comment by jaibatrik** [comment]
Merged PR #19. Will be published in the next version.
