### ISSUE TITLE
Cannot find name 'SocialUser'

### ISSUE THREAD

**Issue by novacommerce** [abacritt/angular4-social-login#20]
Cannot find name 'SocialUser'. How to fix?

ERROR in src/app/app.component.ts(12,17): error TS2304: Cannot find name 'SocialUser'.

webpack: Compiling...
Date: 2017-11-03T16:07:37.658Z
Hash: 71d981ca744881c80e1e
Time: 301ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry]
chunk {main} main.bundle.js (main) 25.6 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 598 kB [initial]
chunk {styles} styles.bundle.js (styles) 33.4 kB [initial]
chunk {vendor} vendor.bundle.js (vendor) 9.81 MB [initial]

**Comment by jaibatrik** [comment]
What is your import statement?

**Comment by hopefulRialist** [comment]
Hello i'm also having the same issue

ERROR in src/app/app.module.ts(48,27): error TS2304: Cannot find name 'LoginOpt'.
src/app/navigation/sidenav-list/sidenav-list.component.ts(15,17): error TS2304: Cannot find name 'SocialUser'.

This is my import statement at my app.module.ts
import { SocialLoginModule, AuthServiceConfig } from 'angularx-social-login';
import { GoogleLoginProvider} from 'angularx-social-login';

and this is the import statement at sidenav-list.component.ts
import { AuthService } from 'angularx-social-login';
import { GoogleLoginProvider } from 'angularx-social-login';

**Comment by jaibatrik** [comment]
In `sidenav-list.component.ts` you need to import the SocialUser and LoginOpt interfaces.

**Comment by hopefulRialist** [comment]
It worked! Thank you!
