### ISSUE TITLE
complie error

### ISSUE THREAD

**Issue by junimohano** [abacritt/angular4-social-login#3]
ERROR in Error encountered resolving symbol values statically. Calling function 'SocialLoginModule', function calls are not supported. Consider replacing the function or lambda with a
 reference to an exported function, resolving symbol AppModule in D:/GitHub/hairbook/src/app/app.module.ts, resolving symbol AppModule in D:/GitHub/hairbook/src/app/app.module.ts

how to fix it.....

**Comment by jaibatrik** [comment]
Check this [document](https://github.com/abacritt/angular4-social-login/blob/master/README-AOT.md).

**Comment by junimohano** [comment]
thank you !!!!!!!

**Comment by junimohano** [comment]
It is working for debuging mode. not working for prod....

ERROR in Unexpected value 'SocialLoginModule in D:/GitHub/hairbook/node_modules/angular4-social-login/dist/lib/sociallogin.module.d.ts' imported by the module 'AppModule in D:/GitHub/
hairbook/src/app/app.module.ts'. Please add a @NgModule annotation.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'D:\GitHub\hairbook\src'
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts

I got this Error..
How to fix it ?

**Comment by jaibatrik** [comment]
Are you in a Angular CLI project? How are you compiling for prod? Is it `ng build --prod`?

**Comment by junimohano** [comment]
yes right, I am using Angular CLI and ng build --prod

**Comment by junimohano** [comment]
Have you tried angular v4.3.1 and cli v1.2.4 ?

**Comment by junimohano** [comment]
I followed your AOT code.

errors when I do "ng s"
`ERROR in SocialLoginModule is not an NgModule`

errors when I build as prod mode.
`ERROR in Unexpected value 'SocialLoginModule in D:/GitHub/hairbook/node_modules/angular4-social-login/dist/lib/sociallogin.module.d.ts' imported by the module 'SharedModule in D:/GitH
ub/hairbook/src/app/shared/shared.module.ts'. Please add a @NgModule annotation.`
`ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'D:\GitHub\hairbook\src'
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts`

Is there any resolution?
Please help me.

**Comment by jaibatrik** [comment]
I'll check and let you know, meanwhile you can also try to find a solution.

**Comment by junimohano** [comment]
thank you.. i will wait.

**Comment by jaibatrik** [comment]
I could tell that it used to work with earlier version. I'll try to build with newer angular compiler. 

Meanwhile. as a workaround, you can clone this repository, copy the `lib` folder in your project and use it.

**Comment by junimohano** [comment]
thank you, do you know which version is working ? I will downgrade of it.

let me know which version is working

**Comment by junimohano** [comment]
By the way, thank you for help.

It is working that you gave a way.

I look forward to hearing until you upload new version of it.

Thanks,

**Comment by jaibatrik** [comment]
https://github.com/angular/angular-cli/issues/7237

**Comment by DeonBonthuys** [comment]
Hi,

I take it this is still an open issue since i have the same problem.

**Comment by jaibatrik** [comment]
Should get resolved with the latest commit (v1.0.12 in npm). Reopen if you still see the issue.

**Comment by alambertt** [comment]
> Thank you.. It is working for debuging mode. not working for prod....
> 
> ERROR in Unexpected value 'SocialLoginModule in D:/GitHub/hairbook/node_modules/angular4-social-login/dist/lib/sociallogin.module.d.ts' imported by the module 'AppModule in D:/GitHub/
> hairbook/src/app/app.module.ts'. Please add a @NgModule annotation.
> 
> ERROR in ./src/main.ts
> Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'D:\GitHub\hairbook\src'
> @ ./src/main.ts 3:0-74
> @ multi ./src/main.ts
> 
> I got this Error..
> How to fix it ?

I got this error with `ng build --prod` but with `ng build` all fine. 

I want to use `--prod` what can I do??
