### ISSUE TITLE
FB login not working on demo site

### ISSUE THREAD

**Issue by bencameron00** [abacritt/angular4-social-login#32]
Hi
It seems the demo site is broken. I am seeing the same issue in my app. Has something at FB changed?
![capture](https://user-images.githubusercontent.com/5983049/33804211-0da06ca4-dd98-11e7-8599-f9d1fda0564c.PNG)

**Comment by jaibatrik** [comment]
It appears to be working for me. Can you check once again.

**Comment by adamtester** [comment]
The facebook app needs to become 'live', I get the same error

**Comment by jaibatrik** [comment]
Apparently, I need to have a privacy policy URL to make this app public.

**Comment by adamtester** [comment]
Lol! Pointing to this repo will probably be sufficient

**Comment by jaibatrik** [comment]
I did that itself - pointed to this issue 🤣  Hope it works. Closing the issue as of now.
