### ISSUE TITLE
localdeploy script not found

### ISSUE THREAD

**Issue by c00** [abacritt/angular4-social-login#33]
I'm trying to test some local changes, but your instructions for running a local test of the demo package doesn't seem to work, because the `localdeploy` script is missing.

Command tried:  
`npm run localdeploy`

Error returned:  
`npm ERR! missing script: localdeploy`

**Comment by jaibatrik** [comment]
Yeah, it was available in the older version. Could you please follow these steps - 

```sh
cd demo
npm install
ng serve
```

I am also updating the README.
