### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically. Calling function 'SocialLoginModule'

### ISSUE THREAD

**Issue by sachinghalmegit** [abacritt/angular4-social-login#4]
after "ng serve" i'm getting below error, 
![image](https://user-images.githubusercontent.com/26225407/29030899-268df5ba-7baa-11e7-9144-472d5782f22c.png)

after saving any file from work space, it compiles all project files and this time it works well.
I'm not getting why this happens. Could you please someone help me to get out of this. Please find below image for the same.

![image](https://user-images.githubusercontent.com/26225407/29031134-dab87696-7baa-11e7-852b-befe91eef39d.png)

**Comment by jaibatrik** [comment]
Ideally, fixing #3 should fix this as well. I am looking into a possible fix.

**Comment by sachinghalmegit** [comment]
Please find below app.module.ts file


import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import {FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';
import { SocialLoginModule, AuthServiceConfig,GoogleLoginProvider, FacebookLoginProvider } from "angular4-social-login";
import { StarRatingModule } from 'angular-star-rating';
import { AppComponent } from './app.component';
import { LandingPageComponent } from './landing-page/landing-page.component';
import { AppHeaderComponent } from './app-header/app-header.component';
let config = new AuthServiceConfig([
{
id: GoogleLoginProvider.PROVIDER_ID,
provider: new GoogleLoginProvider("")
},
{
id: FacebookLoginProvider.PROVIDER_ID,
provider: new FacebookLoginProvider("")
}
]);
export function provideConfig() {
return config;
}
@NgModule({
declarations: [
AppComponent,
LandingPageComponent,
AppHeaderComponent
],
imports: [
BrowserModule,
FormsModule,
HttpModule,
StarRatingModule.forRoot(),
RouterModule.forRoot([
{ path: 'landing', component: LandingPageComponent },
{ path: '' , redirectTo:'landing',pathMatch:'full' }
]),
SocialLoginModule.initialize(config)
],
providers: [{ provide: AuthServiceConfig,
useFactory: provideConfig
}],
bootstrap: [AppComponent ]
})
export class AppModule { }

**Comment by debasishsarkar** [comment]
Hi team,
I am new to this angular4 designing, and facing the same issue as everyone. I upgraded the modules to latest 4.3.5. Is the module still incompatible or anyone found to get it worked?

**Comment by jaibatrik** [comment]
Try the workaround mentioned in this [document](https://github.com/abacritt/angular4-social-login/blob/master/README-AOT.md).
