### ISSUE TITLE
Google does not return token

### ISSUE THREAD

**Issue by MosheWorld** [abacritt/angular4-social-login#40]
Hey there, I am trying to get token from google and it seems I receive all the data and not the important one, any suggestions?

This is what I get from them.

email:"mmoshikooclassifiedgmail.com",
id:"claasified",
name:"Moshe",
photoUrl:"https://lh4.googleusercontent.com/dC7huzWQ1Sc/AAAAAAAAAAI/.../s96-c/photo.jpg",
provider:"GOOGLE"

Thanks for help!

**Comment by jinryung1983** [comment]
I've seen issue code in google-login-provider.ts file.
let token = this.auth2.currentUser.get().getAuthResponse(true).access_token;

this code should be as following
let token = this.auth2.currentUser.get().getAuthResponse().id_token;

it may typo. :)

**Comment by kangw3n** [comment]
i think access_token is correct in this situation?

token which pass back to user should be access_token for oAuth authentication?

**Comment by kangw3n** [comment]
for @MosheWorld  

i think npm for this project hasn't been update yet.
@jaibatrik might need republish to npm for your issues to work.

or u can manually changing your local angular4-social-login.umd.js by adding the following code inside
GoogleLoginProvider prototype fn

` var token = _this.auth2.currentUser.get().getAuthResponse(true).access_token;` 

and return it back as user.authToken property

**Comment by jaibatrik** [comment]
@MosheWorld @kangw3n I have pushed it to the npm. Thanks!

**Comment by jaibatrik** [comment]
@MosheWorld You may need to do `npm install angular4-social-login@latest` to get the changes.
