### ISSUE TITLE
Use first name and last name instead of just name

### ISSUE THREAD

**Issue by movsar** [abacritt/angular4-social-login#9]
When using just name, sometimes it can be confusing which one is actually first and which is the last names, please add this feature.

**Comment by jaibatrik** [comment]
Will look into this. Let's see if Google and Facebook supports this in the basic authentication withour any scope.

**Comment by mgsnikips** [comment]
Hi, i will follow this enhancement, is usefull for my projects to have Giben Name and Family Name.
In google api y can take it with: 
var profile = googleUser.getBasicProfile();
  console.log('Given Name: ' + profile.getGivenName());
  console.log('Family Name: ' + profile.getFamilyName());
Thanks

**Comment by mgsnikips** [comment]
I solved it. In the node_modules in my project, in angular4-social-login carpet, i modified the nexts files:
index.js
angular4-social-login.umd.js
entities/user.d.ts

adding 
     user.givenName = profile.getGivenName();
    user.FamilyName = profile.getFamilyName();
in google providers method.
and in user model (entities/user.d.ts)
    givenName:string;
    FamilyName:string;

this for version of angular4-social-login 1.0.12

**Comment by jaibatrik** [comment]
Fixed via 1950b09a3d29c5f857bf8c5422335f5e35c3fb73.
